Script started on 2016年03月14日 (週一) 21時06分50秒
]0;E64036211@2015cpp: ~E64036211@2015cpp:~$ whoami;ped
E64036211
No command 'ped' found, did you mean:
 Command 'pd' from package 'puredata-core' (universe)
 Command 'ed' from package 'ed' (main)
 Command 'sed' from package 'sed' (main)
 Command 'pen' from package 'pen' (universe)
 Command 'pee' from package 'moreutils' (universe)
 Command 'red' from package 'ed' (main)
 Command 'psed' from package 'perl' (main)
 Command 'jed' from package 'jed' (universe)
 Command 'pwd' from package 'coreutils' (main)
 Command 'fped' from package 'fped' (universe)
 Command 'pev' from package 'pev' (universe)
ped: command not found
]0;E64036211@2015cpp: ~E64036211@2015cpp:~$ whoami;pwd
E64036211
/home/E64036211
]0;E64036211@2015cpp: ~E64036211@2015cpp:~$ git config -l
user.name=changyuanhua
user.email=chang19960726@gmail.com
]0;E64036211@2015cpp: ~E64036211@2015cpp:~$ git clone https://github.com/changyuanhua/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;E64036211@2015cpp: ~E64036211@2015cpp:~$ exit

Script done on 2016年03月14日 (週一) 21時10分46秒
